In [1]:
import torch
from pytorch_metric_learning.losses import NTXentLoss

C:\Users\jsfz\anaconda3\envs\pytorch17\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
NTXentLoss

pytorch_metric_learning.losses.ntxent_loss.NTXentLoss

In [35]:
a = torch.randn(3, 4)

In [36]:
a

tensor([[ 0.4610,  0.3638, -0.2998, -0.1891],
        [ 0.1334,  0.0743, -0.2128, -1.0367],
        [ 0.5977,  0.0201,  0.8429,  0.3610]])

In [37]:
embeddings = torch.cat([a, a], dim=0)

In [38]:
embeddings

tensor([[ 0.4610,  0.3638, -0.2998, -0.1891],
        [ 0.1334,  0.0743, -0.2128, -1.0367],
        [ 0.5977,  0.0201,  0.8429,  0.3610],
        [ 0.4610,  0.3638, -0.2998, -0.1891],
        [ 0.1334,  0.0743, -0.2128, -1.0367],
        [ 0.5977,  0.0201,  0.8429,  0.3610]])

In [23]:
loss_fn = NTXentLoss()

In [24]:
from pytorch_metric_learning.utils import loss_and_miner_utils as lmu

In [39]:
labels = torch.arange(3)
labels = torch.cat([labels, labels], dim=0)

In [40]:
labels

tensor([0, 1, 2, 0, 1, 2])

In [41]:
loss = loss_fn(embeddings, labels)

In [42]:
loss

tensor(0.0007)